apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    uid: VictoriaMetrics
    url: http://ops-victoria:8428
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus-local
    url: http://ops-prometheus:9090
    isDefault: false
    editable: true
    version: 1
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
